// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbjlutzpxbwbyfihbpwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5iamx1dHpweGJ3YnlmaWhicHd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTg2NTMsImV4cCI6MjA2MTc3NDY1M30.MURDAq4iNSWC8ZprLl5Pm2qyJEyTa7BgG0wQkuOGD0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);